### ISSUE TITLE
Issue BTVN Buổi 2

### ISSUE THREAD

**Issue by MinhPT-99** [namxg6626/namxg6626.github.io#2]
Bài chia ruộng hợp lí rồi đấy. Nếu div màu vàng mà bé hơn thì gộp chung vào với 2 cái trên cho dễ quản lí nhé. Với cả màn hình của a bé quá :( dưới 1300px cơ haizzz nên bài của e bị tràn ra ngoài. Nghĩ cách khắc phục nhé. Good job!!!

**Comment by namxg6626** [comment]
Ok a, lần sau e để width 100% :v
